# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 950d09113e054c6cffbc11ba75385e31135e3064a505bf2d3ae1c5c429118bef46382413550c44fd16aea033df000261e5b0e1f92d8d57898c79d74689bc73f5

test:
  secret_key_base: d6d0a390ad4ae335c58ff909bfd47a96397a72a2cf7a588b254d8cc9e14ccc6fdc73954afdf8f1b40d72bce02677c5884469baf7010e8d6cb7167266c36b337e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
